
server {
listen 80;
server_name localhost;

root /usr/share/nginx/html;
index index.html;

location / {
try_files uriuri uriuri/ /index.html;
}

location /api/ {
proxy_pass [http://backend:8000/](http://backend:8000/);
proxy_set_header Host host;proxysetheaderX−Real−IPhost;
        proxy_set_header X-Real-IP host;proxys​eth​eaderX−Real−IPremote_addr;
proxy_set_header X-Forwarded-For scheme;
}
}

